CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE ALUNO(
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(20),
	ALTURA DOUBLE(3,2),
	APROVADO BOOLEAN
);

DROP TABLE PROFESSOR;

CREATE TABLE PROFESSOR(
	CODIGO INT,
	NOME VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO ALUNO VALUES ("ANDRE","ANDRE@CEPEP.COM","123456","1.75",TRUE);
INSERT INTO ALUNO VALUES ("LEONARDO","LEONARDO@CEPEP.COM","123456","1.77",TRUE);
INSERT INTO ALUNO VALUES ("PLATINI","PLATINI@CEPEP.COM","123456","1.83",TRUE);
INSERT INTO ALUNO VALUES ("JOSE","JOSE@CEPEP.COM","123456","1.68",FALSE);
INSERT INTO ALUNO VALUES ("ANTONIO","ANTONIO@CEPEP.COM","123456","1.69",FALSE);

INSERT INTO PROFESSOR VALUES (1,"ARISTENIO");
INSERT INTO PROFESSOR VALUES (2,"MARCELO");
INSERT INTO PROFESSOR VALUES (3,"VALDO");

DELETE FROM ALUNO;

SELECT * FROM ALUNO;

SELECT NOME, EMAIL FROM ALUNO;

SELECT * FROM ALUNO,PROFESSOR;

SELECT a.NOME,p.NOME FROM ALUNO a ,PROFESSOR p;

SELECT a.NOME as NOME_ALUNO,p.NOME as NOME_PROFESSOR FROM ALUNO as a ,PROFESSOR as p;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA = 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <> 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <= 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA >= 1.75;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO IS TRUE;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO IS FALSE;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.APROVADO = 0;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.NOME IS NOT NULL;

SELECT A.NOME AS NOME_ALUNO, A.APROVADO FROM ALUNO AS A WHERE A.NOME IS NULL;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA BETWEEN 1.70 AND 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA <= 1.80 AND A.ALTURA >= 1.70;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA NOT BETWEEN 1.70 AND 1.80;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "ANTONIO";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "ANTO%";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.NOME LIKE "%L%";

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA IN (1.75, 1.83, 1.69);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA NOT IN (1.75, 1.83, 1.69);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE !(A.ALTURA = 1.75);

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE NOT A.ALTURA = 1.75;

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE (A.ALTURA > 1.70) AND (APROVADO IS TRUE) AND (A.NOME LIKE "A%");

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE (A.ALTURA > 1.70) && (APROVADO IS TRUE) && (A.NOME LIKE "A%");

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE ((A.ALTURA > 1.70) OR (APROVADO IS TRUE)) AND (A.NOME LIKE "A%"); 

SELECT A.NOME AS NOME_ALUNO, A.ALTURA FROM ALUNO AS A WHERE A.ALTURA > 1.70 XOR A.APROVADO IS TRUE;

SELECT * FROM ALUNO ORDER BY NOME;

SELECT * FROM ALUNO ORDER BY ALTURA,NOME;

SELECT * FROM ALUNO ORDER BY NOME DESC;

SELECT * FROM ALUNO ORDER BY NOME ASC;

SELECT COUNT(*) FROM ALUNO;

SELECT AVG(ALTURA) FROM ALUNO;

SELECT SUM(ALTURA) FROM ALUNO;

SELECT MAX(ALTURA) FROM ALUNO;

SELECT MIN(ALTURA) FROM ALUNO;

SELECT VARIANCE(ALTURA) FROM ALUNO;

ALTER TABLE ALUNO ADD SEXO VARCHAR(1) NOT NULL;

UPDATE ALUNO SET SEXO = "M";

INSERT INTO ALUNO VALUES ("MARIA","MARIA@CEPEP.COM","123456","1.65",TRUE,"F");
INSERT INTO ALUNO VALUES ("JOAQUINA","JOAQUINA@CEPEP.COM","123456","1.63",TRUE,"F");

SELECT * FROM ALUNO WHERE SEXO LIKE "M";
SELECT * FROM ALUNO WHERE SEXO LIKE "F";

SELECT APROVADO, COUNT(*) FROM ALUNO GROUP BY APROVADO;

SELECT SEXO,APROVADO, COUNT(*) FROM ALUNO GROUP BY SEXO,APROVADO;

SELECT COUNT(*) AS TOTAL_APROVADO FROM ALUNO WHERE APROVADO IS TRUE AND NOME LIKE "A%" XOR "%A" GROUP BY APROVADO;

SELECT * FROM ALUNO;

SELECT DISTINCT(NOME) FROM ALUNO; 

ALTER TABLE ALUNO ADD CIDADE VARCHAR(100) NOT NULL;

UPDATE ALUNO SET CIDADE = "FORTALEZA";

UPDATE ALUNO SET CIDADE = "JUAZEIRO" WHERE NOME LIKE "A%";

SELECT DISTINCT(CIDADE) FROM ALUNO;

SELECT * FROM ALUNO LIMIT 5;

SELECT COUNT(*) FROM ALUNO;

SELECT * FROM ALUNO ORDER BY NOME;

SELECT * FROM ALUNO ORDER BY NOME LIMIT 2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 0,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 2,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 4,2;
SELECT * FROM ALUNO ORDER BY NOME LIMIT 6,2;
