CREATE DATABASE SYSBANK;

USE SYSBANK;

CREATE TABLE BANCO(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	SIGLE VARCHAR(3),
	CODIGO VARCHAR(4) UNIQUE
);

INSERT INTO BANCO (NOME,SIGLE,CODIGO) VALUES ("BANCO DO BRASIL","BB","001");
INSERT INTO BANCO (NOME,SIGLE,CODIGO) VALUES ("CAIXA ECONOMICA","CXE","002");
INSERT INTO BANCO (NOME,SIGLE,CODIGO) VALUES ("BRADESCO","BRA","004");

SELECT * FROM BANCO;

CREATE TABLE AGENCIA(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	CODIGO VARCHAR(4),
	BANCO_ID BIGINT,
	FOREIGN KEY(BANCO_ID) REFERENCES BANCO(ID),
	UNIQUE INDEX(CODIGO,BANCO_ID)
);

INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE1","001",1);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE2","002",1);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE3","003",1);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE12","001",2);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE22","002",2);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE33","003",2);
INSERT INTO AGENCIA (NOME,CODIGO,BANCO_ID) VALUES ("AGE13","001",3);

SELECT * FROM AGENCIA;

CREATE TABLE CLIENTE(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255),
	EMAIL VARCHAR(100) UNIQUE,
	SEXO ENUM("M","F")
);

CREATE TABLE PERFIL(
	ID BIGINT PRIMARY KEY,
	PROFISSAO VARCHAR(255),
	HOBBIES VARCHAR(255),
	GOSTO_MUSICAL VARCHAR(255),
	FOREIGN KEY(ID) REFERENCES CLIENTE(ID)
);