/* INSERT DE REGISTRO*/
INSERT INTO TABELA (CAMPO1,CAMPO2) VALUES ('TESTE3',8976.45);

/*SELEÇÃO DE REGISTRO*/
SELECT CAMPO1,CAMPO2 FROM TABELA;
SELECT * FROM TABELA;

/* ATUALIZAR TODOS OS REGISTROS*/
UPDATE TABELA SET CAMPO1 = 'TESTE', CAMPO2 = 5646.65;
/* ATUALIZAR UM REGISTRO ESPECIFICO*/
UPDATE TABELA SET CAMPO1 = 'TESTE2', CAMPO2 = 1.1, CAMPO3 = 2, CAMPO4=5 WHERE CAMPO1='TESTE3';

INSERT INTO TABELA (CAMPO1,CAMPO2,CAMPO3,CAMPO4) VALUES ('TESTE3',8976.45,456,5);

DELETE FROM TABELA WHERE CAMPO1='TESTE';